# Generated by Django 4.0.3 on 2022-05-16 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loai',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MatHang',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField(default='', max_length=255)),
                ('gia', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('loai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supermarket.loai')),
            ],
        ),
    ]
